
FROM node:20-alpine AS build

WORKDIR /app


COPY package*.json ./


RUN npm install

# Copy source
COPY . .

# Build TypeScript
RUN npm run build



FROM node:20-alpine

WORKDIR /app


COPY package*.json ./


RUN npm install --omit=dev


COPY --from=build /app/dist ./dist

EXPOSE 4000

ENV NODE_ENV=production

CMD ["node", "dist/server.js"]
